### ISSUE TITLE
macOS Installer Support

### ISSUE THREAD

**Issue by ebresie** [codelerity/netbeans-installers#2]
Installer presently supports Windows and Linux flavor of installers but lacks macOS support.

(Based on discussion I know this is coming but figured I would raise it in support of when it's able to be implemented).

**Comment by neilcsmith-net** [comment]
It's done.  Actually the discussion was separate (although related) to this, as we use NBPackage rather than the code used for the ASF installers.

https://github.com/codelerity/netbeans-installers/releases/tag/v13-macos-build1
https://www.codelerity.com/netbeans/
