### ISSUE TITLE
Better description of netbeans 14 appimage for Raspberry Pi

### ISSUE THREAD

**Issue by SimonGreenaway** [codelerity/netbeans-installers#5]
It might be nice to add to the description that this is a 32bit version and won't work with 64bit Raspberry pi OS. Maybe add a 64bit one too?

**Comment by neilcsmith-net** [comment]
Thanks for the report.  Yes, I'll update the description when we do NetBeans 15 shortly.

Does the 32bit version not run at all?  I don't have a Pi set up with 64-bit at the moment - was under the impression that it should still run.

We may consider dropping the AppImages for Pi entirely based on download stats.  Do you find it a better option than the all-arch DEB?

**Comment by SimonGreenaway** [comment]
It failed with an ELF 32bit compatibility error (sorry, I deleted the installer and cannot repeat). I suspect if I had the 32bit toolchain it would have worked, but that's a lot of bloat.

I didn't try the .DEB (I used the binary download from Apache), I'll give it a try.

**Comment by neilcsmith-net** [comment]
Description updated with NetBeans 15 release.  Have kept the arm32 AppImage for now, but still monitoring usage.  I doubt we'll provide a 64-bit Arm AppImage.  Might consider DEB with Arm JDK.
