### ISSUE TITLE
Apache Netbeans 15 +jdk 18 Deb Security Notice

### ISSUE THREAD

**Issue by sandrewsjr** [codelerity/netbeans-installers#6]
WARNING: package com.apple.eio not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/usr/lib/apache-netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release

**Comment by neilcsmith-net** [comment]
Thanks, but this is an upstream and known issue. You'll see the same warnings running any variant of NetBeans on JDK 18. Work is ongoing to fix, but they are just warnings at present so don't affect NetBeans usage.
