### ISSUE TITLE
ubuntu can't run

### ISSUE THREAD

**Issue by quantrpeter** [codelerity/netbeans-installers#7]
Hi
   After installed "apache-netbeans_15-1_all.deb", i can see the app icon, once I clicked it, nothing come out. If I type "netbeans" in terminal, it works. Please help
Peter

**Comment by neilcsmith-net** [comment]
Not sure.  Have you got a stray .desktop file somewhere?

From terminal try `gtk-launch apache-netbeans-ide-15` - what happens?

What about output of `find /usr -name "*.desktop" | grep netbeans` and `find ~ -name "*.desktop" | grep netbeans`?

**Comment by neilcsmith-net** [comment]
Any further info?  Problem solved?  Can I close this?

**Comment by quantrpeter** [comment]
thanks a lot
